---
- name: creating files or directories
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: create a file
    file:
      path: /home/ansadmin/testfile
#     path: /home/ansadmin/dir1
#     state: touch
      state: absent
      mode: 0644
      owner: ansadmin
      group: ansadmin
