---
- name: install & uninstall multiple packages
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: uninstall packages
      yum: 
        name: ['git', 'wget',]
        state: removed
    - name: install packages
      yum:
        name: ['telnet', 'tree', 'make']
        state: installed
